### PR TITLE
Readme Updates, Add Logo, minor tweaks to code

### PR DESCRIPTION
**Pull request by hansonjw**

### CODE REVIEW

**Review by aadi1988 — COMMENTED** [review]
do we need the script_v2.js?? can we remove it if it's not needed?

**Comment by hansonjw** [comment]
> do we need the script_v2.js?? can we remove it if it's not needed?

No we definitely don't need that...There is not reference to the file and I tried to delete it entirely...

**Comment by hansonjw** [comment]
> > do we need the script_v2.js?? can we remove it if it's not needed?
> 
> No we definitely don't need that...There is not reference to the file and I tried to delete it entirely...

Can you reject and I'll re-push my code?

**Comment by aadi1988** [comment]
> > > do we need the script_v2.js?? can we remove it if it's not needed?
> > 
> > 
> > No we definitely don't need that...There is not reference to the file and I tried to delete it entirely...
> 
> Can you reject and I'll re-push my code?

sure

**Comment by aadi1988** [comment]
couldd you please remove the script_v2.js?

**Pull request closed without merging**
